name: training_journal_app
description: Mobile app for Android made for storing training data.

publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.0
  sqflite_common_ffi: 2.3.0
  path: 1.8.3
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true