name: training_journal_app
description: Mobile app for Android made for storing training data.

publish_to: 'none'

environment:
  sdk: ^3.4.0
  flutter: any

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: any
  sqflite: ^2.0.0
  sqflite_common_ffi: any
  path: any
  intl: any
  cupertino_icons: any
  material_color_utilities: any
  charts_flutter_maintained: any
  timezone: any

dependency_overrides:
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any


flutter:
  uses-material-design: true