name: training_journal_app
description: Mobile app for Android made for storing training data.

publish_to: 'none'

environment:
  sdk: ^3.2.0
  flutter: ^3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.3.0+4
  path: 1.8.3
  intl: any
  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.5.0
  charts_flutter_maintained: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true